name: Check Model Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-models:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        # Only need pidgin itself to read model config
        pip install -e .
    
    - name: Check for model updates
      id: check
      run: |
        python scripts/check_model_updates.py
    
    - name: Create issue if changes found
      if: steps.check.outputs.has_changes == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const issueBody = `${{ steps.check.outputs.issue_body }}`;
          
          // Check if a similar issue already exists
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'model-updates',
            state: 'open'
          });
          
          // Only create if no open model update issues
          if (issues.data.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🤖 Model and SDK Updates Detected',
              body: issueBody,
              labels: ['model-updates', 'maintenance']
            });
          } else {
            console.log('Model update issue already exists, skipping creation');
          }